### ISSUE TITLE
[Join Request] Contributer/Maintainer

### ISSUE THREAD

**Issue by aetherith** [BSData/konflikt47#1]
I'd like to start working on the KF47 ruleset to make it viable for BattleScribe use.

**Comment by amis92** [comment]
Hello, @aetherith . Please accept the invitation in the email or on the [repo page](https://github.com/BSData/konflikt47/invitations). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!

PS Great to see someone experienced in development. :)
