### ISSUE TITLE
Heavy armour senior officer not recognized as commander

### ISSUE THREAD

**Issue by Neremsa** [BSData/konflikt47#12]
**Describe the bug**
When creating a roster and selecting one (or multiple) heavy armour senior officer, I have the error "must have 1 more selections from Commander (minimum 1)" which should not appear since a senior officer is a commander.

**To Reproduce**
1. Create a Konflikt 47 roster 
2. Select "Reinforced Platoon"
3. On the Headquarters section, select and add Heavy Armour Senior Officer to the roster
4. The error "must have 1 more selections from Commander (minimum 1)" should appear

**Expected behavior**
Normally the error should not appear since this unit is a commander.

**Screenshots**
![image](https://user-images.githubusercontent.com/112026049/186521787-cdae90ce-7887-4c0d-900e-d00c69758382.png)

**Device and data (please complete the following information):**
 - OS: Android & Windows 10
 - BattleScribe version : 2.03.21
 - Release version : V3

**Comment by ingeanus** [comment]
Added the commander tag to the unit that it was missing.
