### ISSUE TITLE
[Anon] Bug report: Great_Britain_and_the_Commonwealth.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/konflikt47#14]
**File:** Great_Britain_and_the_Commonwealth.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** On the Grizzly Medium Assault Walker I believe the points are incorrect, when clicking on the unit and selecting the quality, the correct values of 200 and 245 are displayed. However, when the unit appears in the overall list, there seems to be 200pts added on, so a regular unit is 400 and a veteran unit is 445.
I hope I am correct is noticing this and not just overlooking something, hope this helps!

**Comment by ingeanus** [comment]
Fixed in commit #15 , an old way of calculating points didn't get removed from it, so it was counting twice.
