### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by amis92** [BSData/konflikt47#3]
Hi @aetherith it seems you've made some files on `develop` branch. They're not released to the public since they're not on master.

Is there any value in them? Are you going to update them? Or can this repo be deleted?

**Comment by amis92** [comment]
I'll be archiving the repository in the meantime. If you want it reactivated, please open an issue at https://github.com/BSData/catalogue-development

**Comment by ingeanus** [comment]
Closing since the repo is now unarchived and being maintained.
