### ISSUE TITLE
Repo releases

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/konflikt47#6]
@ingeanus Hello! I am an admin for the BsData group and wanted to chat about the releases you’ve been doing but I couldn’t find you on our discord. 

Thanks for contributing and updating the repo! The amount of releases you’re doing back to back is discouraged though. Our data host appspot tends to not agree with rapid fire releases. There are time that after a release it will go down for a period. So rapidly releasing can increase that chance. Over in the 40k repo we usually stick to one release a week. At the fastest I’d recommend no more than one per day. 

If you want to chat feel free to ping me over on our discord!

**Comment by ingeanus** [comment]
Good to know! I'll definitely keep them way down then. I also messaged you in Discord as well.
