### ISSUE TITLE
[Anon] Bug report: Germany.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/konflikt47#8]
**File:** Germany.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Unit missing
Heavy sniper team, page 130 of the main rulebook
32 pts (regular), 41 pts (veteran)
2 men
Anti tank rifle and SMG
Add panzerfaust +5 pts
Team weapon

**Comment by ingeanus** [comment]
Errata changed the Heavy Sniper Team to Light Anti Tank Team. They're included, just under that name (and weird selection options).
